SET foreign_key_checks = 0;
DELETE FROM m_appuser_role where appuser_id >1;
ALTER TABLE m_appuser_role AUTO_INCREMENT=1;
DELETE FROM m_role where id > 1;
ALTER TABLE m_role AUTO_INCREMENT=1;
DELETE FROM m_appuser where id >1 ;
ALTER TABLE m_appuser AUTO_INCREMENT=1;
TRUNCATE m_staff;
DELETE FROM `m_office` WHERE  `id` > 1;
TRUNCATE m_product_loan;
TRUNCATE m_savings_product;
TRUNCATE m_charge;
TRUNCATE m_product_loan_charge;
TRUNCATE m_fund;
TRUNCATE m_group;
TRUNCATE m_client;
TRUNCATE m_group_client;
TRUNCATE m_calendar;
TRUNCATE m_calendar_instance;
TRUNCATE m_loan;
TRUNCATE m_loan_disbursement_detail;
TRUNCATE m_loan_charge;
TRUNCATE `m_loan_charge_paid_by`;
TRUNCATE m_loan_recalculation_details;
TRUNCATE `m_loan_overdue_installment_charge`;
TRUNCATE m_loan_officer_assignment_history;
TRUNCATE `m_payment_detail`;
TRUNCATE `m_interest_rate_slab`;
TRUNCATE m_loan_repayment_schedule;
TRUNCATE m_loan_repayment_schedule_history;
TRUNCATE m_loan_transaction;
DELETE FROM m_code where is_system_defined=0;
ALTER TABLE m_code AUTO_INCREMENT=18;
DELETE FROM m_code_value WHERE id>9;
ALTER TABLE m_code_value AUTO_INCREMENT=9;
TRUNCATE m_note;
TRUNCATE `acc_gl_journal_entry`;
TRUNCATE `acc_gl_account`;
TRUNCATE `acc_gl_account`;
TRUNCATE `m_meeting`;
TRUNCATE `m_client_attendance`;
DELETE FROM m_role_permission where role_id <>1;
TRUNCATE `m_deposit_product_recurring_detail`;
TRUNCATE `m_deposit_product_term_and_preclosure`;
TRUNCATE `m_deposit_account_recurring_detail`;
TRUNCATE `m_deposit_account_term_and_preclosure`;
TRUNCATE `m_deposit_product_interest_rate_chart`;
TRUNCATE `m_interest_rate_chart`;
TRUNCATE `m_deposit_product_interest_rate_chart`;
TRUNCATE `m_mandatory_savings_schedule`;
TRUNCATE `m_savings_account_interest_rate_slab`;
TRUNCATE `m_savings_account_interest_rate_chart`;
TRUNCATE `m_savings_account_transaction`;
TRUNCATE `m_savings_account`;
TRUNCATE `m_savings_account_charge`;
TRUNCATE `m_savings_account_charge_paid_by`;
TRUNCATE `m_savings_account_interest_rate_chart;
TRUNCATE `m_savings_account_interest_rate_slab`;
TRUNCATE `m_savings_account_transaction`;
TRUNCATE `m_savings_product_charge`;
TRUNCATE `m_deposit_account_term_and_preclosure`;
TRUNCATE `m_savings_account_interest_rate_chart`;
TRUNCATE `m_savings_account_interest_rate_slab`;
TRUNCATE `x_registered_table`;

SET foreign_key_checks = 1;